// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Caption struct {
	ID          string    `json:"id"`
	ClipID      string    `json:"clip_id"`
	Format      string    `json:"format"`
	CaptionPath string    `json:"caption_path"`
	BurnedID    int64     `json:"burned_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Clip struct {
	ID        string          `json:"id"`
	VideoID   string          `json:"video_id"`
	ClipPath  string          `json:"clip_path"`
	StartTime string          `json:"start_time"`
	EndTime   string          `json:"end_time"`
	Duration  sql.NullFloat64 `json:"duration"`
	Label     string          `json:"label"`
	Status    string          `json:"status"`
	ErrorMsg  sql.NullString  `json:"error_msg"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Job struct {
	ID          string         `json:"id"`
	JobType     string         `json:"job_type"`
	Payload     string         `json:"payload"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	Attempts    string         `json:"attempts"`
	MaxAttempts string         `json:"max_attempts"`
	LastError   sql.NullString `json:"last_error"`
	QueuedAt    time.Time      `json:"queued_at"`
	StartedAt   sql.NullTime   `json:"started_at"`
	EndedAt     sql.NullTime   `json:"ended_at"`
}

type Segment struct {
	ID           int64   `json:"id"`
	TranscriptID string  `json:"transcript_id"`
	StartTime    float64 `json:"start_time"`
	EndTime      float64 `json:"end_time"`
	Text         string  `json:"text"`
	Confidence   float64 `json:"confidence"`
}

type Transcript struct {
	ID             string         `json:"id"`
	VideoID        string         `json:"video_id"`
	Language       string         `json:"language"`
	Model          string         `json:"model"`
	FullText       string         `json:"full_text"`
	TranscriptPath sql.NullString `json:"transcript_path"`
	Status         string         `json:"status"`
	ErrorMsg       sql.NullString `json:"error_msg"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Video struct {
	ID           string         `json:"id"`
	Filename     string         `json:"filename"`
	OriginalPath string         `json:"original_path"`
	Duration     float64        `json:"duration"`
	Filesize     int64          `json:"filesize"`
	Width        int64          `json:"width"`
	Height       int64          `json:"height"`
	Fps          float64        `json:"fps"`
	Codec        string         `json:"codec"`
	Status       string         `json:"status"`
	ErrorMsg     sql.NullString `json:"error_msg"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
