// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CancelJob(ctx context.Context, id string) (Job, error)
	CompleteJob(ctx context.Context, id string) (Job, error)
	CreateCaption(ctx context.Context, arg CreateCaptionParams) (Caption, error)
	CreateClip(ctx context.Context, arg CreateClipParams) (Clip, error)
	CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteCaption(ctx context.Context, id string) error
	DeleteClip(ctx context.Context, id string) error
	DeleteSegmentByTranscript(ctx context.Context, transcriptID string) error
	DeleteVideo(ctx context.Context, id string) error
	DequeueNextJob(ctx context.Context) (Job, error)
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	FailJob(ctx context.Context, arg FailJobParams) (Job, error)
	GetCaption(ctx context.Context, id string) (Caption, error)
	GetClip(ctx context.Context, id string) (Clip, error)
	GetJob(ctx context.Context, id string) (Job, error)
	GetTranscript(ctx context.Context, id string) (Transcript, error)
	GetTranscriptByVideo(ctx context.Context, videoID string) (Transcript, error)
	GetVideo(ctx context.Context, id string) (Video, error)
	InsertSegment(ctx context.Context, arg InsertSegmentParams) (Segment, error)
	ListCaptionsByClip(ctx context.Context, clipID string) ([]Caption, error)
	ListClipsByVideo(ctx context.Context, videoID string) ([]Clip, error)
	ListJobsByStatus(ctx context.Context, status string) ([]Job, error)
	ListSegmentsByTranscript(ctx context.Context, transcriptID string) ([]Segment, error)
	ListVideos(ctx context.Context) ([]Video, error)
	RequeueJob(ctx context.Context, id string) (Job, error)
	UpdateClipsStatus(ctx context.Context, arg UpdateClipsStatusParams) (Clip, error)
	UpdateTranscriptDone(ctx context.Context, arg UpdateTranscriptDoneParams) (Transcript, error)
	UpdateTranscriptStatus(ctx context.Context, arg UpdateTranscriptStatusParams) (Transcript, error)
	UpdateVideoMetadata(ctx context.Context, arg UpdateVideoMetadataParams) (Video, error)
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) (Video, error)
}

var _ Querier = (*Queries)(nil)
