// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const cancelJob = `-- name: CancelJob :one
UPDATE jobs SET status = 'cancelled', ended_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? RETURNING id, job_type, payload, status, priority, attempts, max_attempts, last_error, queued_at, started_at, ended_at
`

func (q *Queries) CancelJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, cancelJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :one
UPDATE jobs SET status = 'done', ended_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? RETURNING id, job_type, payload, status, priority, attempts, max_attempts, last_error, queued_at, started_at, ended_at
`

func (q *Queries) CompleteJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, completeJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createCaption = `-- name: CreateCaption :one
INSERT INTO captions (id, clip_id, format, caption_path, burned_id) VALUES (?, ?, 'srt', ?, ?) RETURNING id, clip_id, format, caption_path, burned_id, created_at
`

type CreateCaptionParams struct {
	ID          string `json:"id"`
	ClipID      string `json:"clip_id"`
	CaptionPath string `json:"caption_path"`
	BurnedID    int64  `json:"burned_id"`
}

func (q *Queries) CreateCaption(ctx context.Context, arg CreateCaptionParams) (Caption, error) {
	row := q.db.QueryRowContext(ctx, createCaption,
		arg.ID,
		arg.ClipID,
		arg.CaptionPath,
		arg.BurnedID,
	)
	var i Caption
	err := row.Scan(
		&i.ID,
		&i.ClipID,
		&i.Format,
		&i.CaptionPath,
		&i.BurnedID,
		&i.CreatedAt,
	)
	return i, err
}

const createClip = `-- name: CreateClip :one
INSERT INTO clips (id, video_id, clip_path, start_time, end_time, label, status) VALUES (?, ?, ?, ?, ?, ?, 'pending') RETURNING id, video_id, clip_path, start_time, end_time, duration, label, status, error_msg, created_at, updated_at
`

type CreateClipParams struct {
	ID        string `json:"id"`
	VideoID   string `json:"video_id"`
	ClipPath  string `json:"clip_path"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
	Label     string `json:"label"`
}

func (q *Queries) CreateClip(ctx context.Context, arg CreateClipParams) (Clip, error) {
	row := q.db.QueryRowContext(ctx, createClip,
		arg.ID,
		arg.VideoID,
		arg.ClipPath,
		arg.StartTime,
		arg.EndTime,
		arg.Label,
	)
	var i Clip
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ClipPath,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Label,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTranscript = `-- name: CreateTranscript :one
INSERT INTO transcripts (id, video_id, language, model, status) VALUES (?, ?, ?, 'small', 'pending') RETURNING id, video_id, language, model, full_text, transcript_path, status, error_msg, created_at, updated_at
`

type CreateTranscriptParams struct {
	ID       string `json:"id"`
	VideoID  string `json:"video_id"`
	Language string `json:"language"`
}

func (q *Queries) CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, createTranscript, arg.ID, arg.VideoID, arg.Language)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Model,
		&i.FullText,
		&i.TranscriptPath,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (id, filename, original_path, filesize, status) VALUES (?, ?, ?, ?, 'pending') RETURNING id, filename, original_path, duration, filesize, width, height, fps, codec, status, error_msg, created_at, updated_at
`

type CreateVideoParams struct {
	ID           string `json:"id"`
	Filename     string `json:"filename"`
	OriginalPath string `json:"original_path"`
	Filesize     int64  `json:"filesize"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.ID,
		arg.Filename,
		arg.OriginalPath,
		arg.Filesize,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.Duration,
		&i.Filesize,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Codec,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCaption = `-- name: DeleteCaption :exec
DELETE FROM captions WHERE id = ?
`

func (q *Queries) DeleteCaption(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCaption, id)
	return err
}

const deleteClip = `-- name: DeleteClip :exec
DELETE FROM clips WHERE id = ?
`

func (q *Queries) DeleteClip(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClip, id)
	return err
}

const deleteSegmentByTranscript = `-- name: DeleteSegmentByTranscript :exec
DELETE FROM segments WHERE transcript_id = ?
`

func (q *Queries) DeleteSegmentByTranscript(ctx context.Context, transcriptID string) error {
	_, err := q.db.ExecContext(ctx, deleteSegmentByTranscript, transcriptID)
	return err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos WHERE id = ?
`

func (q *Queries) DeleteVideo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVideo, id)
	return err
}

const dequeueNextJob = `-- name: DequeueNextJob :one
UPDATE jobs SET status = 'running', started_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'), attempts = attempts + 1 WHERE id = (
   SELECT id FROM jobs WHERE status = 'queued' AND attempts < max_attempts ORDER BY priority DESC, queued_at ASC LIMIT 1
) RETURNING id, job_type, payload, status, priority, attempts, max_attempts, last_error, queued_at, started_at, ended_at
`

func (q *Queries) DequeueNextJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRowContext(ctx, dequeueNextJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (id, job_type, payload, priority) VALUES (?, ?, ?, ?) RETURNING id, job_type, payload, status, priority, attempts, max_attempts, last_error, queued_at, started_at, ended_at
`

type EnqueueJobParams struct {
	ID       string `json:"id"`
	JobType  string `json:"job_type"`
	Payload  string `json:"payload"`
	Priority string `json:"priority"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.ID,
		arg.JobType,
		arg.Payload,
		arg.Priority,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE jobs SET status = 'failed', last_error = ?, ended_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? RETURNING id, job_type, payload, status, priority, attempts, max_attempts, last_error, queued_at, started_at, ended_at
`

type FailJobParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        string         `json:"id"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, failJob, arg.LastError, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getCaption = `-- name: GetCaption :one
SELECT id, clip_id, format, caption_path, burned_id, created_at FROM captions WHERE id = ? LIMIT 1
`

func (q *Queries) GetCaption(ctx context.Context, id string) (Caption, error) {
	row := q.db.QueryRowContext(ctx, getCaption, id)
	var i Caption
	err := row.Scan(
		&i.ID,
		&i.ClipID,
		&i.Format,
		&i.CaptionPath,
		&i.BurnedID,
		&i.CreatedAt,
	)
	return i, err
}

const getClip = `-- name: GetClip :one
SELECT id, video_id, clip_path, start_time, end_time, duration, label, status, error_msg, created_at, updated_at FROM clips WHERE id = ? LIMIT 1
`

func (q *Queries) GetClip(ctx context.Context, id string) (Clip, error) {
	row := q.db.QueryRowContext(ctx, getClip, id)
	var i Clip
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ClipPath,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Label,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, job_type, payload, status, priority, attempts, max_attempts, last_error, queued_at, started_at, ended_at FROM jobs WHERE id = ? LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getTranscript = `-- name: GetTranscript :one
SELECT id, video_id, language, model, full_text, transcript_path, status, error_msg, created_at, updated_at FROM transcripts WHERE id = ? LIMIT 1
`

func (q *Queries) GetTranscript(ctx context.Context, id string) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, getTranscript, id)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Model,
		&i.FullText,
		&i.TranscriptPath,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscriptByVideo = `-- name: GetTranscriptByVideo :one
SELECT id, video_id, language, model, full_text, transcript_path, status, error_msg, created_at, updated_at FROM transcripts WHERE video_id = ? LIMIT 1
`

func (q *Queries) GetTranscriptByVideo(ctx context.Context, videoID string) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, getTranscriptByVideo, videoID)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Model,
		&i.FullText,
		&i.TranscriptPath,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, filename, original_path, duration, filesize, width, height, fps, codec, status, error_msg, created_at, updated_at FROM videos WHERE id = ? LIMIT 1
`

func (q *Queries) GetVideo(ctx context.Context, id string) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.Duration,
		&i.Filesize,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Codec,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSegment = `-- name: InsertSegment :one
INSERT INTO segments (transcript_id, start_time, end_time, text, confidence) VALUES (?, ?, ?, ?, ?) RETURNING id, transcript_id, start_time, end_time, text, confidence
`

type InsertSegmentParams struct {
	TranscriptID string  `json:"transcript_id"`
	StartTime    float64 `json:"start_time"`
	EndTime      float64 `json:"end_time"`
	Text         string  `json:"text"`
	Confidence   float64 `json:"confidence"`
}

func (q *Queries) InsertSegment(ctx context.Context, arg InsertSegmentParams) (Segment, error) {
	row := q.db.QueryRowContext(ctx, insertSegment,
		arg.TranscriptID,
		arg.StartTime,
		arg.EndTime,
		arg.Text,
		arg.Confidence,
	)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.TranscriptID,
		&i.StartTime,
		&i.EndTime,
		&i.Text,
		&i.Confidence,
	)
	return i, err
}

const listCaptionsByClip = `-- name: ListCaptionsByClip :many
SELECT id, clip_id, format, caption_path, burned_id, created_at FROM captions WHERE clip_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListCaptionsByClip(ctx context.Context, clipID string) ([]Caption, error) {
	rows, err := q.db.QueryContext(ctx, listCaptionsByClip, clipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Caption
	for rows.Next() {
		var i Caption
		if err := rows.Scan(
			&i.ID,
			&i.ClipID,
			&i.Format,
			&i.CaptionPath,
			&i.BurnedID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClipsByVideo = `-- name: ListClipsByVideo :many
SELECT id, video_id, clip_path, start_time, end_time, duration, label, status, error_msg, created_at, updated_at FROM clips WHERE video_id = ? ORDER BY start_time ASC
`

func (q *Queries) ListClipsByVideo(ctx context.Context, videoID string) ([]Clip, error) {
	rows, err := q.db.QueryContext(ctx, listClipsByVideo, videoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Clip
	for rows.Next() {
		var i Clip
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ClipPath,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
			&i.Label,
			&i.Status,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, job_type, payload, status, priority, attempts, max_attempts, last_error, queued_at, started_at, ended_at FROM jobs WHERE status = ? ORDER BY queued_at DESC
`

func (q *Queries) ListJobsByStatus(ctx context.Context, status string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.QueuedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentsByTranscript = `-- name: ListSegmentsByTranscript :many
SELECT id, transcript_id, start_time, end_time, text, confidence FROM segments WHERE transcript_id = ? ORDER BY start_time ASC
`

func (q *Queries) ListSegmentsByTranscript(ctx context.Context, transcriptID string) ([]Segment, error) {
	rows, err := q.db.QueryContext(ctx, listSegmentsByTranscript, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.StartTime,
			&i.EndTime,
			&i.Text,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideos = `-- name: ListVideos :many
SELECT id, filename, original_path, duration, filesize, width, height, fps, codec, status, error_msg, created_at, updated_at FROM videos ORDER BY created_at DESC
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.OriginalPath,
			&i.Duration,
			&i.Filesize,
			&i.Width,
			&i.Height,
			&i.Fps,
			&i.Codec,
			&i.Status,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueJob = `-- name: RequeueJob :one
UPDATE jobs SET status = 'queued' WHERE id = ? RETURNING id, job_type, payload, status, priority, attempts, max_attempts, last_error, queued_at, started_at, ended_at
`

func (q *Queries) RequeueJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, requeueJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.QueuedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const updateClipsStatus = `-- name: UpdateClipsStatus :one
UPDATE clips SET status = ?, error_msg = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now') WHERE id = ? RETURNING id, video_id, clip_path, start_time, end_time, duration, label, status, error_msg, created_at, updated_at
`

type UpdateClipsStatusParams struct {
	Status   string         `json:"status"`
	ErrorMsg sql.NullString `json:"error_msg"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateClipsStatus(ctx context.Context, arg UpdateClipsStatusParams) (Clip, error) {
	row := q.db.QueryRowContext(ctx, updateClipsStatus, arg.Status, arg.ErrorMsg, arg.ID)
	var i Clip
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ClipPath,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Label,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTranscriptDone = `-- name: UpdateTranscriptDone :one
UPDATE transcripts SET full_text = ?, transcript_path = ?, status = 'done',  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? RETURNING id, video_id, language, model, full_text, transcript_path, status, error_msg, created_at, updated_at
`

type UpdateTranscriptDoneParams struct {
	FullText       string         `json:"full_text"`
	TranscriptPath sql.NullString `json:"transcript_path"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateTranscriptDone(ctx context.Context, arg UpdateTranscriptDoneParams) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, updateTranscriptDone, arg.FullText, arg.TranscriptPath, arg.ID)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Model,
		&i.FullText,
		&i.TranscriptPath,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTranscriptStatus = `-- name: UpdateTranscriptStatus :one
UPDATE transcripts SET status = ?, error_msg = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? RETURNING id, video_id, language, model, full_text, transcript_path, status, error_msg, created_at, updated_at
`

type UpdateTranscriptStatusParams struct {
	Status   string         `json:"status"`
	ErrorMsg sql.NullString `json:"error_msg"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateTranscriptStatus(ctx context.Context, arg UpdateTranscriptStatusParams) (Transcript, error) {
	row := q.db.QueryRowContext(ctx, updateTranscriptStatus, arg.Status, arg.ErrorMsg, arg.ID)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Language,
		&i.Model,
		&i.FullText,
		&i.TranscriptPath,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideoMetadata = `-- name: UpdateVideoMetadata :one
UPDATE videos SET duration = ?, width = ?, height = ?, fps = ?, codec = ?, status = 'ready', updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? RETURNING id, filename, original_path, duration, filesize, width, height, fps, codec, status, error_msg, created_at, updated_at
`

type UpdateVideoMetadataParams struct {
	Duration float64 `json:"duration"`
	Width    int64   `json:"width"`
	Height   int64   `json:"height"`
	Fps      float64 `json:"fps"`
	Codec    string  `json:"codec"`
	ID       string  `json:"id"`
}

func (q *Queries) UpdateVideoMetadata(ctx context.Context, arg UpdateVideoMetadataParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, updateVideoMetadata,
		arg.Duration,
		arg.Width,
		arg.Height,
		arg.Fps,
		arg.Codec,
		arg.ID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.Duration,
		&i.Filesize,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Codec,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :one
UPDATE videos SET status = ?, error_msg = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? RETURNING id, filename, original_path, duration, filesize, width, height, fps, codec, status, error_msg, created_at, updated_at
`

type UpdateVideoStatusParams struct {
	Status   string         `json:"status"`
	ErrorMsg sql.NullString `json:"error_msg"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, updateVideoStatus, arg.Status, arg.ErrorMsg, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.OriginalPath,
		&i.Duration,
		&i.Filesize,
		&i.Width,
		&i.Height,
		&i.Fps,
		&i.Codec,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
