// models (structs) for clip timeline segments

package timeline

import (
	"fmt"
)

// segments for clips generated by the  timeline service

type Segments struct {
	Index     int
	StartTime float64
	EndTime   float64
	Duration  float64 // end time  - start time
	Label     string  // readable format - clip_0_00:00:00-00:00:30
}

type Strategy string

const (
	StrategyFixed Strategy = "fixed"
)

// options struct

type Options struct {
	ClipLength float64

	MinLength float64 // min-length range should be between 0 to cliplength

	Overlap  float64 // if first video's end part becomes start part of second video, then overlap happens
	Strategy Strategy
}

// some validation for keeping somethings to default

func (op *Options) validate() error {

	if op.ClipLength <= 0 {
		return fmt.Errorf("timeline: clip length must be > 0, got %.3f", op.ClipLength)
	}

	if op.MinLength < 0 {
		return fmt.Errorf("timeline: min length must be  >= 0, got %.3f", op.MinLength)
	}

	if op.MinLength > op.ClipLength {
		return fmt.Errorf("timeline: min length must not exceed the clip length, got %.3f", op.MinLength)
	}

	if op.Overlap < 0 {
		return fmt.Errorf("timeline: overlap must be >= 0, got %.3f", op.Overlap)
	}

	if op.Overlap >= op.ClipLength {
		return fmt.Errorf("timeline: overlap must not be exceed cliplength, got %.3f", op.Overlap)
	}

	if op.MinLength == 0 {
		op.MinLength = op.ClipLength * 0.5
	}

	if op.Strategy == "" {
		op.Strategy = StrategyFixed
	}

	return nil
}
